import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Image from "next/image";
import background from "./assets/images/background.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "H.J. Cartwright | Author",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div id="background-wrapper">
          <Image
            src={background}
            alt="Background trees"
            quality="100"
            layout="fill"
            placeholder="blur"
          />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
